services:
  practice_nginx:
    container_name: practice_nginx
    image: practice_nginx:1.0
    restart: on-failure
    build:
      context: ./requirements/nginx
    volumes:
      - resources:/usr/share/nginx/html
    ports:
      - "8090:80"

volumes:
  resources:
    name: resources
